import { defineField, defineType } from "sanity";

export const post = defineType({
  name: "post",
  title: "Blog Post",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (r) => r.required().max(90),
      group: "content",
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
      group: "content",
      description: "Click 'Generate' after writing the title. Keep it short and keyword-rich.",
    }),
    defineField({
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      rows: 3,
      validation: (r) => r.required().max(200),
      description: "1–2 sentences shown on the blog index and in search results.",
      group: "content",
    }),
    defineField({
      name: "coverImage",
      title: "Cover Image",
      type: "image",
      options: { hotspot: true },
      fields: [{ name: "alt", type: "string", title: "Alt text (describe the image)" }],
      group: "content",
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "reference",
      to: [{ type: "author" }],
      group: "content",
    }),
    defineField({
      name: "category",
      title: "Topic Cluster",
      type: "reference",
      to: [{ type: "category" }],
      description: "Which topic cluster does this belong to? Posts in the same cluster link to each other.",
      group: "content",
    }),
    defineField({
      name: "publishedAt",
      title: "Publish Date",
      type: "datetime",
      initialValue: () => new Date().toISOString(),
      group: "content",
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      of: [
        { type: "block" },
        { type: "image", options: { hotspot: true }, fields: [{ name: "alt", type: "string", title: "Alt text" }] },
      ],
      group: "content",
    }),
    defineField({
      name: "relatedPosts",
      title: "Related Posts (internal links)",
      type: "array",
      of: [{ type: "reference", to: [{ type: "post" }] }],
      validation: (r) => r.max(4),
      group: "seo",
    }),
    defineField({
      name: "seoTitle",
      title: "SEO Title (overrides post title in Google)",
      type: "string",
      validation: (r) => r.max(60),
      group: "seo",
    }),
    defineField({
      name: "seoDescription",
      title: "SEO Description",
      type: "text",
      rows: 2,
      validation: (r) => r.max(160),
      group: "seo",
    }),
  ],
  preview: {
    select: { title: "title", media: "coverImage", subtitle: "excerpt" },
  },
});
